name: ItemRename
author: Lopezito
version: 1.0
description: Rename Items
main: com.gmail.lopezitospriter.ItemName.main
commands:
  rename:
    description: Rename Items
    usage: /rename iditem cantidad color newname
    permission: itemrename.rename
    aliases: [rn, xre]
  renamee:
    description: Rename Items
    usage: /renamee iditem cantidad color newname
    permission: itemrename.renamee
    aliases: [rne, xree]
permissions:
    itemrename.*:
        description: All commands of plugin
        default: op
        children:
            xminecraft.rename: true
            xminecraft.renamee: true
    itemrename.rename:
        description: Can use /rename
        default: op
    itemrename.renamee:
        description: Can use /renamee
        default: op